env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - standard
  - 'eslint:recommended'
  - 'plugin:mithril/recommended'
parserOptions:
  ecmaVersion: 12
plugins:
  - mithril
rules: {
    "semi": [2, "always"],
    "space-before-function-paren": ["error", "never"],
    "no-empty": ["error", { "allowEmptyCatch": true }],
    "comma-dangle": ["error", "only-multiline"]
}
